local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>f', function() vim.lsp.buf.format { async = true } end, { desc = "LSP: [F]ormat current buffer" })
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = 'Telescope find files' })
vim.keymap.set('n', '<leader>fg', builtin.live_grep, { desc = 'Telescope live grep' })
vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = 'Telescope buffers' })
vim.keymap.set('n', '<leader>fh', builtin.help_tags, { desc = 'Telescope help tags' })
vim.keymap.set("n", "<leader>e", "<cmd>Neotree filesystem toggle left<CR>",{ desc = "Neo-tree sidebar", })
